# debug: true

spring:
  jpa:
    generate-ddl: true
  rabbitmq:
    host: ${DOCKER_IP}
  redis:
    host: ${DOCKER_IP}
  zipkin:
    base-url: http://${DOCKER_IP}:9411
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true

info:
  id: ${spring.application.name}

server:
  port: ${PORT:${SERVER_PORT:0}}

logging:
  level:
    org:
      springframework:
        security: DEBUG

# com:
#   netflix:
#     eureka: OFF
#     discovery: OFF


endpoints:
  shutdown:
    enabled: true

# eureka:
#   instance:
#     hostname: ${vcap.application.uris[0]:localhost}
#     nonSecurePort: 80
