server:
  port: ${PORT:0}
  context-path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: localhost
  redis:
    host: localhost
    port: 6379
  cloud:
    stream:
      bindings:
        input:
          destination: test
          group: test
          durableSubscription: true
  zipkin:
    host: localhost
    port: 9411
    base-url: http://localhost:9411
    sender:
      type: web

eureka:
  instance:
    instance-id: testing12345
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # instance-id: ${spring.application.name}:${random.int}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
  sessions: NEVER
